### ISSUE TITLE
Redesigning the message element 

### ISSUE THREAD

**Issue by SakshiShah29** [swarnarkadas/ichat_app#40]
The message element can be styled again.
Modifications in the CSS file needed.

I would like to contribute to it.

**Comment by swarnarkadas** [comment]
@SakshiShah29, You are assigned to this issue. First, fetch all the changes made recently in the application.

**Comment by pooranjoyb** [comment]
## I would like to make a small change in the message element container so that the chats looks like the following...

### Sample Image 

<img src="https://thumbs.dreamstime.com/z/chat-box-message-bubbles-balloon-messenger-screen-template-vector-flat-dialog-social-media-application-chatting-interface-171864178.jpg"> 

## Please assign me this issue as no PR has been raised. Would like to work under JWOC 2023  @swarnarkadas

**Comment by SakshiShah29** [comment]
> @SakshiShah29, You are assigned to this issue. First, fetch all the changes made recently in the application.

Yes I am working on it

**Comment by pooranjoyb** [comment]
Please assign me with this one @swarnarkadas 👍

**Comment by swarnarkadas** [comment]
@SakshiShah29, your time period is over. So I am unassigning you from this issue.

**Comment by swarnarkadas** [comment]
@pooranjoyb, You are assigned to this issue.
